// <auto-generated />
using IntermediarioMuitosParaMuitosFluentAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IntermediarioMuitosParaMuitosFluentAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20191005204438_bancoincial")]
    partial class bancoincial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IntermediarioMuitosParaMuitosFluentAPI.Models.Empregado", b =>
                {
                    b.Property<int>("EmpregadoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CPF");

                    b.Property<int>("Idade");

                    b.Property<string>("Nome");

                    b.HasKey("EmpregadoId");

                    b.ToTable("Empregados");
                });

            modelBuilder.Entity("IntermediarioMuitosParaMuitosFluentAPI.Models.EmpregadoTrabalho", b =>
                {
                    b.Property<int>("EmpregadoId");

                    b.Property<int>("TrabalhoId");

                    b.Property<int>("CargaHoraria");

                    b.HasKey("EmpregadoId", "TrabalhoId");

                    b.HasIndex("TrabalhoId");

                    b.ToTable("EmpregadosTrabalhos");
                });

            modelBuilder.Entity("IntermediarioMuitosParaMuitosFluentAPI.Models.Trabalho", b =>
                {
                    b.Property<int>("TrabalhoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome");

                    b.HasKey("TrabalhoId");

                    b.ToTable("Trabalhos");
                });

            modelBuilder.Entity("IntermediarioMuitosParaMuitosFluentAPI.Models.EmpregadoTrabalho", b =>
                {
                    b.HasOne("IntermediarioMuitosParaMuitosFluentAPI.Models.Empregado", "Empregado")
                        .WithMany("EmpregadoTrabalho")
                        .HasForeignKey("EmpregadoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IntermediarioMuitosParaMuitosFluentAPI.Models.Trabalho", "Trabalho")
                        .WithMany("EmpregadoTrabalho")
                        .HasForeignKey("TrabalhoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
